### ISSUE TITLE
Top-level keys should not be options by default.

### ISSUE THREAD

**Issue by acobster** [acobster/wp-yaml-fixtures#10]
With the *possible* exception of a small set of well-known options like `name`, we should not default to interpreting top-level keys as option names and inserting them as options. Instead we should just require a top level `options:` key.

Consider the scenario where we want to define a common structure using YAML's merge syntax:

```
some_stuff: &some_stuff
  a:
  b:
  c:

combined_stuff:
  <<: *some_stuff
  d:
  e:
  f:

other_stuff:
  <<: *some_stuff
  custom: abcd
```

This will be interpreted as defining an option called `some_stuff` with the value of an array, which is probably not what we want. We should be able to do this instead:

```
some_stuff: &some_stuff
  a:
  b:
  c:

options:
  combined_stuff:
    <<: *some_stuff
    d:
    e:
    f:

  other_stuff:
    <<: *some_stuff
    custom: abcd
```

...which will only define `combined_stuff` and `other_stuff` as options.
