### ISSUE TITLE
Syntax sugar for menus

### ISSUE THREAD

**Issue by acobster** [acobster/wp-yaml-fixtures#13]
It'd be handy to be able to do something like this (need to double check YAML syntax):

```yaml
menus:
  primary_menu:
    - home-page-slug
    - another-page
    - yet-another-page:
      - second-level-page:
        - third-level-page
```

...and have it generate the nav hierarchy. In this example, `primary_menu` is the menu slug.
