### ISSUE TITLE
Ability to create fixtures

### ISSUE THREAD

**Issue by acobster** [acobster/wp-yaml-fixtures#7]
It'd be killer to be able to do something like:

```bash
wp fixture create posts 123 456 it-supports-slugs-too
```

...and have the command generate a file from the database, e.g.:

```yaml
posts:
- title: Post 123
  slug: post-123
  author: 3
- title: Post 456
  slug: post-456
  author: 2
- title: It Supports Slugs, Too!
  slug: it-supports-slugs-too
  author: 3
  meta:
    wait_it_gets_meta: Yes, it gets meta fields from the database!!
    no_way_thats_awesome: I know, right?
```
