### ISSUE TITLE
Rewrite blank_slate semantics

### ISSUE THREAD

**Issue by acobster** [acobster/wp-yaml-fixtures#9]
* Honor `all` at top, entity level
* Users by ID, email, username
* Posts by ID, slug
* Associated posts via meta:

```yaml
blank_slate:
  posts:
    - 123
    - id: 456
    - my-slug

  users:
    - 123
    - my_username
    - username: another_username
    - email: ctamayo@sitecrafting.com
      # looks for user's ID in postmeta rows with key `my_posts`
      # and deletes corresponding posts
      delete_posts_with_meta_key: my_posts
```
